ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.petrescue.ApplicationKt.module ]
    }
}

app {
    storage {
        type = "local"
        localPath = "uploads"
    }
    database {
        url = "jdbc:h2:file:./data/petrescue;MODE=PostgreSQL;AUTO_SERVER=TRUE"
        driver = "org.h2.Driver"
    }
    email {
        enabled = false
        enabled = ${?SMTP_ENABLED}
        host = "smtp.gmail.com"
        host = ${?SMTP_HOST}
        port = 587
        port = ${?SMTP_PORT}
        username = ""
        username = ${?SMTP_USERNAME}
        password = ""
        password = ${?SMTP_PASSWORD}
        from = "noreply@petrescue.com"
        from = ${?SMTP_FROM}
    }
    firebase {
        serverKey = ""
        serverKey = ${?FCM_SERVER_KEY}
        apiKey = ""
        apiKey = ${?FIREBASE_API_KEY}
        authDomain = ""
        authDomain = ${?FIREBASE_AUTH_DOMAIN}
        projectId = ""
        projectId = ${?FIREBASE_PROJECT_ID}
        storageBucket = ""
        storageBucket = ${?FIREBASE_STORAGE_BUCKET}
        messagingSenderId = ""
        messagingSenderId = ${?FIREBASE_MESSAGING_SENDER_ID}
        appId = ""
        appId = ${?FIREBASE_APP_ID}
        vapidKey = ""
        vapidKey = ${?FIREBASE_VAPID_KEY}
    }
}
